// <auto-generated />
using System;
using HitCircleAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HitCircleAPI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HitCircleAPI.Models.Entities.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameMode")
                        .HasColumnType("int")
                        .HasColumnName("game_mode");

                    b.Property<string>("OsuUid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("osu_uid");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("platform");

                    b.Property<string>("PlatformUid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("platform_uid");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "PlatformUid")
                        .IsUnique();

                    b.ToTable("user");
                });

            modelBuilder.Entity("HitCircleAPI.Models.Entities.UserOsuInfoHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Accuracy")
                        .HasColumnType("double")
                        .HasColumnName("accuracy");

                    b.Property<int?>("CountryRank")
                        .HasColumnType("int")
                        .HasColumnName("country_rank");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("GameMode")
                        .HasColumnType("int")
                        .HasColumnName("game_mode");

                    b.Property<int?>("GlobalRank")
                        .HasColumnType("int")
                        .HasColumnName("global_rank");

                    b.Property<string>("OsuUid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("osu_uid");

                    b.Property<int?>("PlayCount")
                        .HasColumnType("int")
                        .HasColumnName("play_count");

                    b.Property<int?>("PlayTime")
                        .HasColumnType("int")
                        .HasColumnName("play_time");

                    b.Property<double?>("Pp")
                        .HasColumnType("double")
                        .HasColumnName("pp");

                    b.Property<int?>("TotalHits")
                        .HasColumnType("int")
                        .HasColumnName("total_hits");

                    b.HasKey("Id");

                    b.HasIndex("OsuUid", "Date");

                    b.ToTable("user_osu_info_history");
                });
#pragma warning restore 612, 618
        }
    }
}
